// Phase 2.1: static card, Support, opponent, and flavor data extracted from App07.
export const C={
 David:{name:"David",title:"The Giant Slayer",hp:120,icon:"🪨",rarity:"Common",passive:"Faithful Aim — 25% critical chance.",attacks:[['Sling Shot',2,40],['Five Smooth Stones',4,60]]},
 Jonah:{name:"Jonah",title:"The Reluctant Prophet",hp:110,icon:"🐋",rarity:"Common",passive:"Second Chance — once per battle, survives defeat at 15 HP.",attacks:[['Whale Encounter',2,35],['Nineveh Sprint',3,50]]},
 Andrew:{name:"Andrew",title:"The One Who Brings",hp:105,icon:"🍞",rarity:"Common",passive:"I Know a Guy — when Andrew enters play, gain 1 Prayer if you have 0.",attacks:[['Bring Them Here',1,20],['Five Loaves, Two Fish',2,35]]},
 Thomas:{name:"Thomas",title:"The Doubting Disciple",hp:110,icon:"🤔",rarity:"Common",passive:"Show Me — the first time Thomas takes damage each turn, his next attack gains +10 damage.",attacks:[['Are You Sure?',1,20],['Now I Believe',3,45]]},
 Matthew:{name:"Matthew",title:"The Former Tax Collector",hp:105,icon:"🪙",rarity:"Common",passive:"Tax Collector — attacks have a 25% chance to gain 1 Prayer.",attacks:[['Collect the Due',1,20],['Interest Included',2,35]]},
 Philip:{name:"Philip",title:"The Question Asker",hp:100,icon:"❓",rarity:"Common",passive:"Where Do We Buy Bread? — once per battle below half HP, draw 1 Character if possible.",attacks:[['Can We Find Enough?',1,20],['Follow Me',2,30]]},
 Barnabas:{name:"Barnabas",title:"The Encourager",hp:115,icon:"🤝",rarity:"Common",passive:"Son of Encouragement — when a Character enters your Bench, heal your Active 5 HP.",attacks:[['Cheer Them On',1,20],['Keep Going!',2,30]]},
 Zacchaeus:{name:"Zacchaeus",title:"The Short Collector",hp:95,icon:"🌳",rarity:"Common",passive:"Climb Higher — when Zacchaeus enters play, gain 1 Prayer.",attacks:[['Tax Return',1,25],['Come Down From There',2,40]]},
 Timothy:{name:"Timothy",title:"The Young Disciple",hp:100,icon:"📖",rarity:"Common",passive:"Let No One Despise You — below half HP, deals 15% more damage.",attacks:[['Set an Example',1,20],['Fight the Good Fight',3,45]]},
 Mark:{name:"Mark",title:"The Fast Messenger",hp:100,icon:"⚡",rarity:"Common",passive:"Immediately! — Mark's first attack each battle costs 1 less Prayer.",attacks:[['Immediately!',1,20],['Good News',2,35]]},
 Ruth:{name:"Ruth",title:"The Loyal Daughter",hp:110,icon:"🌾",rarity:"Common",passive:"Where You Go — while Ruth is on the Bench, your Active takes 10% less damage.",attacks:[['Stay With Me',1,20],['Gleaning the Fields',2,30]]},
 Samuel:{name:"Samuel",title:"The Listening Prophet",hp:105,icon:"👂",rarity:"Common",passive:"Speak, Lord — the first Stun each battle is ignored.",attacks:[['Here I Am',1,20],['Thus Says the Lord',3,40]]},
 Daniel:{name:"Daniel",title:"The Lion's Guest",hp:120,icon:"🦁",rarity:"Rare",passive:"Lion's Courage — 25% less incoming damage below half HP.",attacks:[['Lion\'s Courage',2,35],['Den of Lions',4,58]]},
 Gideon:{name:"Gideon",title:"The Unexpected Army",hp:110,icon:"🏺",rarity:"Uncommon",passive:"Small Army — first attack gets +10 damage.",attacks:[['Broken Jar',2,35],['Trumpet Ambush',3,52]]},
 Moses:{name:"Moses",title:"The Sea Splitter",hp:140,icon:"🌊",rarity:"Legendary",passive:"Plague Bringer — attacks apply Plague.",attacks:[['Staff Strike',2,30],['Part the Waters',4,55]]},
 Michael:{name:"Michael",title:"The Archangel",hp:135,icon:"⚔️",rarity:"Legendary",passive:"Guardian's Wing — gains 10 Protection on entry.",attacks:[['Heavenly Strike',2,40],['Archangel\'s Judgment',4,62]]},
 Gabriel:{name:"Gabriel",title:"The Divine Messenger",hp:130,icon:"📯",rarity:"Legendary",passive:"Divine Message — the first time each turn you draw a Support during Upkeep, gain 1 Prayer.",attacks:[['Trumpet of Heaven',2,38],['Messenger\'s Judgment',4,60]]},
 Elijah:{name:"Elijah",title:"Fire From Heaven",hp:125,icon:"🔥",rarity:"Epic",passive:"Fire From Heaven — attacks apply Burn.",attacks:[['Heavenly Fire',3,35],['Mount Carmel',4,60]]},
 Esther:{name:"Esther",title:"For Such a Time",hp:115,icon:"👑",rarity:"Rare",passive:"Royal Favor — first Support used with Esther grants +1 Prayer.",attacks:[['Royal Petition',2,35],['Queen\'s Decree',3,50]]},
 Solomon:{name:"Solomon",title:"The Wise King",hp:125,icon:"📜",rarity:"Legendary",passive:"Wisdom — first Prayer drawn each turn grants +1 extra Prayer.",attacks:[['Proverbial Strike',2,38],['Judgment of Solomon',4,64]]},
 Peter:{name:"Peter",title:"The Rock",hp:130,icon:"🪨",rarity:"Uncommon",passive:"Stand Firm — takes 15% less damage while in play.",attacks:[['Rock Solid',2,34],['Keys of the Kingdom',4,58]]},
 Paul:{name:"Paul",title:"The Apostle",hp:115,icon:"✉️",rarity:"Rare",passive:"Letters of Encouragement — healing Supports restore Paul for 5% extra healing.",attacks:[['Thorn in the Flesh',2,36],['Run the Race',3,54]]},
 Samson:{name:"Samson",title:"Strength From God",hp:145,icon:"💪",rarity:"Epic",passive:"God-Given Strength — deals 10% more damage.",attacks:[['Jawbone Strike',2,42],['Pillars Fall',5,75]]},
 GA:{name:"General Overseer",title:"MYTHICAL • Subject To Change",hp:150,icon:"🔴",rarity:"Mythic",passive:"Presiding Presence — gains 5 Protection at end of turn.",attacks:[['Fifteen More Minutes',1,25],['Amen Brother Jackson',3,45],['Smile Brother Jackson',5,70]]},
 WO:{name:"West Overseer",title:"MYTHICAL • Subject To Change",hp:150,icon:"🔵",rarity:"Mythic",passive:"Regional Momentum — attacks cost 1 less (minimum 1).",attacks:[['One More Thing',2,30],['Long Winded',4,55],['Last Conclusion',5,72]]}
};
export const starter=['David','Jonah','Andrew','Thomas','Matthew','Philip','Barnabas','Zacchaeus','Timothy','Mark','Ruth','Samuel','Daniel','Gideon','Moses','Michael','Gabriel','Elijah','Esther'];
export const mythic=['GA','WO'];
export const supports=[['loaves','Loaves & Fishes','🍞','Heal Active 20 HP.'],['armor','Armor of God','🛡️','Gain 15 Protection.'],['prayer','Prayer Request','🙏','Gain 2 Prayers.'],['trumpets','Trumpets of Jericho','📯','Deal 15 damage.'],['temple','Temple of Solomon','🏛️','Gain 3 Prayers; this card is single-use.'],['manna','Manna From Heaven','🌤️','Heal 10 and gain 1 Prayer.'],['dove','Dove of Peace','🕊️','Remove Burn, Plague, and Stun.'],['commandments','Ten Commandments','📜','Weaken enemy for 2 turns.'],['ark','Noah\'s Ark','🚢','Gain 20 Protection for the next hit.'],['sinai','Mount Sinai','⛰️','Gain 2 Prayers and cleanse Stun.'],['courage','David\'s Courage','🪨','Your next attack gains +15 damage.'],['redsea','Parting of the Red Sea','🌊','Deal 25 damage and apply Weaken for 1 turn.']].map(([id,name,icon,text])=>({id,name,icon,text}));
export const opponents={Pharaoh:{name:'Training Pharaoh',hp:150,icon:'👑',ai:'Aggressive',damage:30,passive:'Royal Command — sometimes hits harder.'},Goliath:{name:'Goliath',hp:190,icon:'🗿',ai:'Power',damage:42,passive:'Giant Strength — heavy swings vary in power.'},Serpent:{name:'The Serpent',hp:135,icon:'🐍',ai:'Poison',damage:22,passive:'Venom — applies Plague.'},Centurion:{name:'Roman Centurion',hp:160,icon:'🛡️',ai:'Balanced',damage:28,passive:'Legion Tactics — sometimes Stuns.'},Solomon:{name:'Strategist Solomon',hp:175,icon:'📜',ai:'Strategist',damage:27,passive:'Wisdom — protects itself when low.'}};
export const lines={Andrew:'🍞 Andrew arrives with something to bring.',Thomas:'🤔 Thomas remains unconvinced.',Matthew:'🪙 Matthew has calculated the odds.',Philip:'❓ Philip has several questions.',Barnabas:'🤝 Barnabas arrives ready to encourage everyone.',Zacchaeus:'🌳 Zacchaeus climbs into the action.',Timothy:'📖 Timothy steps forward to fight the good fight.',Mark:'⚡ Mark arrives. Immediately.',Ruth:'🌾 Ruth arrives with loyalty and determination.',Samuel:'👂 Samuel is listening.',David:'🪨 David steps forward with faith unshaken.',Jonah:'🐋 Jonah arrives reluctantly. Again.',Daniel:'🦁 Daniel enters like he has already met the lions.',Gideon:'🏺 Gideon arrives with jars, trumpets, and a suspiciously small army.',Moses:'🌊 Moses parts the way onto the battlefield.',Michael:'⚔️ Michael descends from Heaven to the battlefield.',Gabriel:'📯 Gabriel arrives with a message from Heaven.',Elijah:'🔥 Elijah calls down fire as he enters.',Esther:'👑 Esther enters — for such a time as this.',Solomon:'📜 Solomon enters with wisdom and several opinions.',Peter:'🪨 Peter stands firm like the rock he is.',Paul:'✉️ Paul arrives with another letter ready.',Samson:'💪 Samson arrives and immediately looks for something to break.',GA:'🔴 The General Overseer arrives. The meeting may take fifteen more minutes.',WO:'🔵 The West Overseer arrives. He has one more thing to say.'};
export const attackFlavor={'Sling Shot':'🪨 Somewhere, a giant suddenly feels nervous.','Five Smooth Stones':'🪨 Five smooth stones. Five problems.','Whale Encounter':'🐋 Jonah attacks. At least there is no whale involved this time.','Nineveh Sprint':'🏃 Jonah finally runs in the right direction.','Lion\'s Courage':'🦁 Daniel refuses to be intimidated.','Den of Lions':'🦁 Daniel brings the full lion-den experience.','Broken Jar':'🏺 Gideon breaks a jar. Subtlety was never the plan.','Trumpet Ambush':'📯 The trumpets sound. The enemy is confused.','Staff Strike':'🌊 Moses raises the staff. Everyone steps back.','Part the Waters':'🌊 Moses makes an opening where there was not one.','Heavenly Strike':'⚔️ Michael raises his heavenly sword.','Trumpet of Heaven':'📯 Gabriel sounds the trumpet of Heaven.','Messenger\'s Judgment':'📯 Gabriel delivers the message with authority.','Archangel\'s Judgment':'✨ Heaven has entered the chat.','Heavenly Fire':'🔥 Elijah looks upward. This is about to get warm.','Mount Carmel':'🔥 Mount Carmel energy activated.','Royal Petition':'👑 Esther makes her request with royal confidence.','Queen\'s Decree':'📜 The battlefield has been formally notified.','Fifteen More Minutes':'🔴 Just fifteen more minutes. Nobody believes him.','Amen Brother Jackson':'🔴 Amen, Brother Jackson!','Smile Brother Jackson':'🔴 Brother Jackson has been officially encouraged.','One More Thing':'🔵 Just one more thing...','Long Winded':'🔵 The attack somehow gets longer.','Last Conclusion':'🔵 This time it really is the last conclusion.'};
